matrix:
  include:
    - os: linux
      dist: bionic
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - gcc-10
            - g++-10
      env:
        - MATRIX_EVAL="export CC=gcc-10 && export CXX=g++-10"

    - os: linux
      dist: bionic
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - sourceline: "deb http://apt.llvm.org/bionic/ llvm-toolchain-bionic-11 main"
              key_url: "https://apt.llvm.org/llvm-snapshot.gpg.key"
          packages:
            - clang-11
            - libc++-11-dev
            - libc++abi-11-dev
      env:
        - MATRIX_EVAL="export CC=clang-11 && export CXX=clang++-11"

    # NOT SUPPORTED NOW
    # - os: osx
    #   osx_image: xcode12
    #   env:
    #     - MATRIX_EVAL="export CC=clang-12 && export CXX=clang++-12"

before_install:
  - sudo apt update
  - eval "${MATRIX_EVAL}"

install:
  - sudo apt install -y cmake make

script:
  - mkdir build && cd build && cmake ../ -DCMAKE_BUILD_TYPE=Debug && make -j2
